### PR TITLE
Add protonDB integration.

### PR DESCRIPTION
**Pull request by aflyingpumpkin**
I got protonDB integration almost working, though I was unable to get it 100% due to a critical error that was occuring. Some help would be greatly appreciated.

The error:
```
error[E0277]: `?` couldn't convert the error to `STError`
```

### CODE REVIEW

**Comment by dmadisetti** [comment]
Yeah, so this is fixable. You'll have to explicitly provide a way for rust to cast the error (you didn't give the type?) into an STError, which you can define here: https://github.com/dmadisetti/steam-tui/blob/main/src/util/error.rs

I don't think this will be your only issue, there may be async problems that will arise once this is fixed. But let me know. I can try to take a stab at this at some point as well.

Just a suggestion on method. Parsing is not async, since we only have 1 thread to communicate with `steamcmd`, so the `await` here is also blocking. This might be noticable for loading time. You can collect the ids here: https://github.com/dmadisetti/steam-tui/blob/445e655722cdba55ebd373b711391ed72e27ef05/src/client.rs#L246, and then use [tokio to map](https://docs.rs/tokio/0.3.0/tokio/stream/trait.StreamExt.html#method.map) those IDs to a proton response here https://github.com/dmadisetti/steam-tui/blob/445e655722cdba55ebd373b711391ed72e27ef05/src/client.rs#L276 (Since this is right before write to disk), and then merge it with the game results, before dumping to disk.

**Comment by dmadisetti** [comment]
Thanks for this! Do you think you'll try to address the async issue?

Also, sorry I don't have this in CI, but try `cargo clippy`

**Comment by aflyingpumpkin** [comment]
I have given it a brief shot, but I am very inexperienced with rust and I lack the knowledge to do it.

**Comment by dmadisetti** [comment]
Yeah, that's fair. I may attempt to do it myself. Do mind if I keep this as a draft and add on to it?

**Comment by aflyingpumpkin** [comment]
Yeah do whatever you want

**Comment by dmadisetti** [comment]
Closed by 0.2.0 ? Let me know what you think

**Pull request closed without merging**
