### PR TITLE
Grey out any games that have an 'uninstalled' status

### PR DESCRIPTION
**Pull request by tajetaje**
Big changes aside from obious UI stuff is the movement of where the status for the shown game is and the addition of a cached check for installed vs unistalled.

### CODE REVIEW

**Comment by dmadisetti** [comment]
I think this is a nice change. Thank you.

I will try it out this afternoon. Code looks good, my one comment is I don't think that the `cache` should be an  `App` attribute, but I get that might be tricky with the borrow checker + loop

**Comment by tajetaje** [comment]
> I think this is a nice change. Thank you.
> 
> 
> 
> I will try it out this afternoon. Code looks good, my one comment is I don't think that the `cache` should be an  `App` attribute, but I get that might be tricky with the borrow checker + loop

Yeah, if you can think of a better place to put it I'd be glad to move it and update the PR, but I couldn't figure a good way

**Comment by dmadisetti** [comment]
Still at work, but thought about this some more. Can't we store status in the game object? https://github.com/dmadisetti/steam-tui/blob/fe535c9e25bea6224bef78011cb68ffde440717d/src/interface.rs#L128

Then no need for cache

**Comment by tajetaje** [comment]
> Still at work, but thought about this some more. Can't we store status in the game object?
> 
> https://github.com/dmadisetti/steam-tui/blob/fe535c9e25bea6224bef78011cb68ffde440717d/src/interface.rs#L128
> 
> Then no need for cache

Maybe, I was just trying to keep the scope of the changes small, but I'll give that a shot

**Comment by tajetaje** [comment]
Alright, list color will now be determined after the games are loaded in, this COULD cause issues, but I think it should work. The way I wrote it should also make it easy to add other install status colors (i.e. needs update) and probably more.

**Comment by dmadisetti** [comment]
Closed by 0.2.0 ? Let me know what you think

**Pull request closed without merging**
